FROM python:3.12.7-alpine

SHELL ["/bin/sh", "-c"]

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN adduser -D -s /bin/bash user && chmod 777 /opt /run

WORKDIR /user

RUN mkdir /user/static && mkdir /user/media && chown -R user:user /user && chmod 755 /user

COPY --chown=user:user ./weatherapp/ .

RUN pip install -r requirements.txt

USER user

CMD ["gunicorn", "-b", "0.0.0.0:8001", "app.wsgi:application"]