services:
  db:
    image: postgres:16.0-alpine
    container_name: dbpostgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_app
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=weatherapp
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./weatherapp/:/usr/src/app/
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

volumes:
  postgres_volume: