# Generated by Django 5.1.2 on 2024-10-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.users')),
            ],
        ),
    ]
